@quotes = (
    "Hold tight, Sir Pinkelton!",
    "Everybody knows I do it like this!",
    "Obsolete Operating System, hold tight.",
    "Ready thyselves...",
    "Who's got this new bread-bin tune?",
    "Easy, bruv.",
    "Shouts to Gunfinger.",
    "Shouts to the 256, hold tight.",
    "Easy now to the people on the bus.",
    "Hold tight, the 674. I see ya, bruv.",
    "Big up VHS.",
    "Nothing wrong with these sounds.",
    "Eliminator.",
    "Hold tight, HTML.",
    "Hold tight, flip flop.",
    "Who wants it?",
    "Out to the shout-out massive. Oi!",
    "Wicked melodies, brilliant.",
    "Hold tight, Slim-B.",
    "I'm keepin' this stuff movin'.",
    "O.M.G.",
    "Hah hah, I'm all good!",
    "Hold tight the 340.",
    "Big up Spodoo."
    "My sound's so crisp.",
    "Hold tight, Diabettie.",
    "Stay with me.",
    "Selecta locked in.",
    "Selecta locked out.",
    "Hold tight, Tarte Tatin.",
    "Shouts to Inhaler",
    "Shouts to Fresh Nuts",
    "Wait for it...",
    "EXECUTIONER",
    "Shouts to all the usual crew at the Mumba Bar",
    "Just getting bugged out here",
    "This one from Mr. Portcullis",
    "Hold tight, the 757. Don't worry bruv I see ya.",
    "Oo, you know it's a Percy!",
    "Insanity",
    "It's the T-WOG\$, rollin' with ya",
    "Shouts to the contact lens solution boys",
    "Check this.",
    "Step to the bass and the lyrical swagger",,
    "UHH THAT'S FILTHY!",
    "420 locked in",
    "Locked in, locked on",
    "Me phone line's melting bruv",
    "Big up Green Lungs and the Arachnid Egg Sac Crew in Isleworth, easy.",
    "Big up Barren Binman, easy.",
    "Keep it locked on, Ursa Minor, easy.",
    "Big up The Terminatorator, easy.",
    "Big up to Susan and Timothy in Barnes, easy.",
    "Shout out to Scum.",
    "Shouts to Infinite Zeros, easy.",
    "Sometimes all I think I need is a pizza box, a playstation controller, and some beats.",
    "I'm not gonna lie to you, I'm annihilated.",
    "Hold tight, Assistant Attorney General.",
    "Hold tight, the 117.",
    "Hold tight, the 343.",
    "Hold tight, Crazy Cane.",
    "UHH THIS IS GREASY.",
    "BRRRRAP!",
    "Big shouts to the 965, locked in, locked on",
    "'outs to the 686.",
    "Easy Ian and the E11 Crew."
);

Irssi::command_bind wog_it => sub {
    my ($data, $server, $witem) = @_;
    my $rand = int(rand($#quotes + 1));
    $witem->command("SAY T-WOG\$ says: ".@quotes[$rand]);
};
